$this->settings["required"] = false;                // Wether is mandatory
$this->settings["min"] = "0";                       // Minimum value. Can be null, when there is no boundary check
$this->settings["max"] = "100";                     // Maximum value. Can be null, when there is no boundary check
$this->settings["init-val"] = "0";                  // Applied when no explicit value is set on the input with the value attribute. Empty string means that the value remains empty on initialization
$this->settings["step"] = "1";                      // Incremental/decremental step on up/down change
$this->settings["decimal"] = "0";                   // Number of decimal points
$this->settings["step-interval"] = "100";           // Refresh rate of the spinner in milliseconds
$this->settings["force-step-divisibility"] = "round"; // How to force the value to be divisible by step value: 'none' | 'round' | 'floor' | 'ceil'
$this->settings["step-interval-delay"] = "500";     // Time in milliseconds before the spinner starts to spin
$this->settings["prefix"] = "";                     // Text before the input
$this->settings["postfix"] = "";                    // Text after the input
$this->settings["prefix-extra-class"] = "";         // Extra class(es) for prefix.
$this->settings["postfix-extra-class"] = "";        // Extra class(es) for postfix.
$this->settings["booster"] = "true";                // If enabled, the the spinner is continually becoming faster as holding the button
$this->settings["boostat"] = "10";                  // Boost at every nth step
$this->settings["max-boosted-step"] = "false";      // Maximum step when boosted
$this->settings["mousewheel"] = "true";             // Enables the mouse wheel to change the value of the input
$this->settings["button-down-class"] = "btn btn-primary"; // Class(es) of down button
$this->settings["button-up-class"] = "btn btn-primary";   // Class(es) of up button.
$this->settings["verticalbuttons"] = "false";       // Enables the traditional up/down buttons