$this->settings["required"] = false; // Wether is mandatory
$this->settings["tooltip"] = "Click here to enter date"; // Information tooltip
$this->settings["format"] = "D/M/YYYY"; // MomentJS Format. Check http://momentjs.com. Gregorian 'D/M/YYYY' 
$this->settings["viewMode"] = 'days'; //  'years','months', 'days'
$this->settings["hijri"] = true; // Calendar Hirji
$this->settings["hijriFormat"] = 'iD/iM/iYYYY'; //  hijri format
$this->settings["useCurrent"] = true; // User date now
$this->settings["minDate"] = '2018-01-15'; // Default 1950-01-01
$this->settings["maxDate"] = '2022-05-06'; //  Default 2070-01-01
$this->settings["viewDate"] = '2020-01-15'; // // date situation
$this->settings["locale"] = 'en-us'; // Default 'ar-sa'
$this->settings["showClear"] = true; // show clear dates button
$this->settings["showClose"] = true; // show close button
$this->settings["showTodayButton"] = true; // // show today button
$this->settings["iconPrevious"] = '<' ; // Text Previous buttom
$this->settings["iconNext"] = '>' ; // Text Next buttom
$this->settings["iconToday"] = 'Today' ; // Text Today buttom
$this->settings["iconClear"] = 'Clear' ; // Text Clear buttom
$this->settings["iconClose"] = 'Close' ; // Text Close buttom
$this->settings["showSwitcher"] = true ; // Switch Hijri to Gregorian
$this->settings["hijriText"] = 'Hijri' ; // Text Hijri buttom
$this->settings["gregorianText"] = 'Gregorian' ; // Text Gregorian buttom
