$this->settings["required"] = true; // Wether is mandatory
$this->settings["apikey"] = ""; // Google Maps API KEY. Refer to https://developers.google.com/maps/documentation/javascript/get-api-key#get-an-api-key
$this->settings["tooltip"] = "Pick a point on the map"; // Information tooltip
$this->settings["width"] = 'auto'; // Width of control
$this->settings["selectbuttontext"] = "Select"; // Caption of button to popup map form
$this->settings["title"] = "Pick a point on the map and press Select";
$this->settings["contentswidth"] = 'default'; // 'default' for window's width - 100
$this->settings["contentsheight"] = ''; // '' for window's height - 100
$this->settings["customcontent"] = ''; // '' leaves content default. Otherwise, fill with path to your custom content file
$this->settings["initiallatitude"] = "-32.934612"; // Default latitude to show if not set
$this->settings["initiallongitude"] = "-60.650093"; // Default longitude to show if not set
$this->settings["radius"] = 20; // Size of circle to show around the point
$this->settings["zoom"] = 15; // Detail map level
$this->settings["mapType"] = "ROADMAP"; // Possible values: ROADMAP, SATELLITE, HYBRID, TERRAIN
$this->settings["scrollwheel"] = 'true'; // Wether using mouse wheel changes zooming
$this->settings["draggable"] = 'true'; // Wether MAP is draggable (not marker);
$this->settings["buttonselecttext"] = "Select"; // Caption of button to select point
$this->settings["buttonselecttooltip"] = "Select current coordinates"; // Tooltip of button to select point
$this->settings["buttonemptytext"] = "Empty"; // Caption of button to make a null selection
$this->settings["buttonemptytooltip"] = "Null selection"; // Tooltip of button to make a null selection
$this->settings["labelsearch"] = "Search:&nbsp;";
$this->settings["placeholdersearch"] = "Type here your search criteria";