$this->settings["required"] = false; // Wether is mandatory
$this->settings["width"] = "500px"; // Width of the control
$this->settings["style"] = ""; // Extra styles to apply to textarea dom element. E.g. "color:red;". Do not input width here. Separate by semicolons
$this->settings["rows"] = 5; // Number of lines of textarea
$this->settings["tooltip"] = "Limited characters / words"; // Information tooltip
$this->settings["placeholder"] = "Limited characters / words"; // Text that appears inside textarea when empty
$this->settings["type"] = "character"; // "character" or "word" to count
$this->settings["min"] = 4; // Minimum number of characters / words
$this->settings["max"] = 20; // Maximum number of characters / words. -1 for unlimited, "auto" to use maxlength dom attribute
$this->settings["countContainerElement"] = "div"; // HTML element to wrap the text count in ("div", "span", etc.)
$this->settings["countContainerClass"] = "telegramia-count-wrapper"; // Class applied to the countContainerElement
$this->settings["inputErrorClass"] = "telegramia-error"; // Error class appended to the input element if error occurs
$this->settings["counterErrorClass"] = "telegramia-error"; // Error class appended to the countContainerElement if error occurs
$this->settings["counterText"] = "Characters count: "; // Counter text
$this->settings["errorTextElement"] = "div"; // Error text element
$this->settings["minimumErrorText"] = "Minimum not met"; // Error message for minimum not met
$this->settings["maximumErrorText"] = "Maximum exceeded"; // Error message for maximum range exceeded
$this->settings["displayErrorText"] = true; // Display error text messages for minimum / maximum values
$this->settings["stopInputAtMaximum"] = true; // Stop further text input if maximum reached
$this->settings["countSpaces"] = true; // Count spaces as character (only for "character" type)
$this->settings["countDown"] = false; // If the counter should deduct from maximum characters / words rather than counting up
$this->settings["countDownText"] = "Remaining characters: "; // Count down text
$this->settings["countExtendedCharacters"] = false; // Count extended UTF-8 characters as 2 bytes (such as Chinese characters)
$this->settings["maxcount"] = "swal('Alert', 'Maximum reached', 'error');"; // Callback: function(element) - Fires when the counter hits the maximum word / character count
$this->settings["mincount"] = "swal('Notice', 'Minimum reached', 'success');"; // Callback: function(element) - Fires when the counter hits the minimum word / character count
$this->settings["init"] = "console.log('init'); console.log(el);"; // Callback: function(element) - Fires after the counter is initially setup